version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -ui -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  pipeline-network:
    driver: bridge

volumes:
  consul-data: