quarkus:
  # Cache configuration for gRPC channels
  cache:
    caffeine:
      "grpc-channels":
        expire-after-write: 10m
        maximum-size: 100


# Test profile  
"%test":
  quarkus:
    log:
      level: INFO
    # Consul configuration
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}