quarkus:
  http:
    port: 38007  # Dev port for parser module
  grpc:
    server:
      port: 38007  # Dev port for parser module
  log:
    level: DEBUG
    console:
      enable: true
    category:
      "com.rokkon":
        level: DEBUG
