quarkus:
  http:
    port: 38006  # Dev port for embedder module
  grpc:
    server:
      port: 38006  # Dev port for embedder module
  log:
    level: DEBUG
    console:
      enable: true
    category:
      "com.rokkon":
        level: DEBUG

  # Development-specific settings
  opentelemetry:
    enabled: false  # Disable OpenTelemetry in dev mode

  # Development-specific container settings
  container-image:
    build: false
    push: false

# Use local file system for processing buffer in dev mode
processing:
  buffer:
    enabled: true
    directory: ${java.io.tmpdir}/embedder-dev-output

# Disable GPU for development (unless you have a compatible GPU)
djl:
  pytorch:
    use-gpu: false
