/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    ConfigSelector: typeof import('./components/ConfigSelector.vue')['default']
    ConnectHealthCheck: typeof import('./components/ConnectHealthCheck.vue')['default']
    DataSeedingEnhanced: typeof import('./components/DataSeedingEnhanced.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MetadataEditor: typeof import('./components/MetadataEditor.vue')['default']
    ModuleRegistry: typeof import('./components/ModuleRegistry.vue')['default']
    ParserDocEditor: typeof import('./components/ParserDocEditor.vue')['default']
    PipeDocEditor: typeof import('./components/PipeDocEditor.vue')['default']
    ProcessDocument: typeof import('./components/ProcessDocument.vue')['default']
    RepositoryConfigDialog: typeof import('./components/RepositoryConfigDialog.vue')['default']
    RepositoryConnectionStatus: typeof import('./components/RepositoryConnectionStatus.vue')['default']
    RequestExecutor: typeof import('./components/RequestExecutor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeedDataBuilder: typeof import('./components/SeedDataBuilder.vue')['default']
    SimpleJsonFormsTest: typeof import('./components/SimpleJsonFormsTest.vue')['default']
    UniversalConfigCard: typeof import('./components/UniversalConfigCard.vue')['default']
    UniversalConfigCardV2: typeof import('./components/UniversalConfigCardV2.vue')['default']
    VuetifyConfigCard: typeof import('./components/VuetifyConfigCard.vue')['default']
  }
}
