/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    ConfigSelector: typeof import('./components/ConfigSelector.vue')['default']
    DataSeedingEnhanced: typeof import('./components/DataSeedingEnhanced.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModuleRegistry: typeof import('./components/ModuleRegistry.vue')['default']
    MongoDBConfig: typeof import('./components/MongoDBConfig.vue')['default']
    ProcessDocument: typeof import('./components/ProcessDocument.vue')['default']
    RequestExecutor: typeof import('./components/RequestExecutor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeedDataBuilder: typeof import('./components/SeedDataBuilder.vue')['default']
    UniversalConfigCard: typeof import('./components/UniversalConfigCard.vue')['default']
    VuetifyConfigCard: typeof import('./components/VuetifyConfigCard.vue')['default']
  }
}
