# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector_service_simple.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pipeline_core_types_pb2 as pipeline__core__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onnector_service_simple.proto\x12\x19io.pipeline.search.engine\x1a\x19pipeline_core_types.proto\"\xf2\x03\n\x10\x43onnectorRequest\x12\x16\n\x0e\x63onnector_type\x18\x01 \x01(\t\x12\x14\n\x0c\x63onnector_id\x18\t \x01(\t\x12\x33\n\x08\x64ocument\x18\x02 \x01(\x0b\x32!.io.pipeline.search.model.PipeDoc\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12<\n\nbatch_info\x18\x04 \x01(\x0b\x32#.io.pipeline.search.model.BatchInfoH\x00\x88\x01\x01\x12V\n\x0e\x63ontext_params\x18\x05 \x03(\x0b\x32>.io.pipeline.search.engine.ConnectorRequest.ContextParamsEntry\x12 \n\x13suggested_stream_id\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08priority\x18\x07 \x01(\x05H\x02\x88\x01\x01\x12\x1e\n\x11\x63onnector_version\x18\x08 \x01(\tH\x03\x88\x01\x01\x1a\x34\n\x12\x43ontextParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\r\n\x0b_batch_infoB\x16\n\x14_suggested_stream_idB\x0b\n\t_priorityB\x14\n\x12_connector_version\"I\n\x11\x43onnectorResponse\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x83\x01\n\x0f\x43onnectorEngine\x12p\n\x13processConnectorDoc\x12+.io.pipeline.search.engine.ConnectorRequest\x1a,.io.pipeline.search.engine.ConnectorResponseB7\n\x1cio.pipeline.processor.engineB\x15\x43onnectorServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connector_service_simple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034io.pipeline.processor.engineB\025ConnectorServiceProtoP\001'
  _globals['_CONNECTORREQUEST_CONTEXTPARAMSENTRY']._options = None
  _globals['_CONNECTORREQUEST_CONTEXTPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CONNECTORREQUEST']._serialized_start=89
  _globals['_CONNECTORREQUEST']._serialized_end=587
  _globals['_CONNECTORREQUEST_CONTEXTPARAMSENTRY']._serialized_start=461
  _globals['_CONNECTORREQUEST_CONTEXTPARAMSENTRY']._serialized_end=513
  _globals['_CONNECTORRESPONSE']._serialized_start=589
  _globals['_CONNECTORRESPONSE']._serialized_end=662
  _globals['_CONNECTORENGINE']._serialized_start=665
  _globals['_CONNECTORENGINE']._serialized_end=796
# @@protoc_insertion_point(module_scope)
