# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connector_service_simple_pb2 as connector__service__simple__pb2


class ConnectorEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processConnectorDoc = channel.unary_unary(
                '/io.pipeline.search.engine.ConnectorEngine/processConnectorDoc',
                request_serializer=connector__service__simple__pb2.ConnectorRequest.SerializeToString,
                response_deserializer=connector__service__simple__pb2.ConnectorResponse.FromString,
                )


class ConnectorEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def processConnectorDoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processConnectorDoc': grpc.unary_unary_rpc_method_handler(
                    servicer.processConnectorDoc,
                    request_deserializer=connector__service__simple__pb2.ConnectorRequest.FromString,
                    response_serializer=connector__service__simple__pb2.ConnectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.pipeline.search.engine.ConnectorEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectorEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def processConnectorDoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/io.pipeline.search.engine.ConnectorEngine/processConnectorDoc',
            connector__service__simple__pb2.ConnectorRequest.SerializeToString,
            connector__service__simple__pb2.ConnectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
