# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pipeline_core_types_pb2 as pipeline__core__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65ngine_service.proto\x12\x19io.pipeline.search.engine\x1a\x19pipeline_core_types.proto\"\x99\x01\n\x12PipeStreamResponse\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x38\n\x06status\x18\x02 \x01(\x0e\x32(.io.pipeline.search.engine.ProcessStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03*5\n\rProcessStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xc7\x02\n\x10PipeStreamEngine\x12\\\n\x0etestPipeStream\x12$.io.pipeline.search.model.PipeStream\x1a$.io.pipeline.search.model.PipeStream\x12g\n\x10processPipeAsync\x12$.io.pipeline.search.model.PipeStream\x1a-.io.pipeline.search.engine.PipeStreamResponse\x12l\n\x11processPipeStream\x12$.io.pipeline.search.model.PipeStream\x1a-.io.pipeline.search.engine.PipeStreamResponse(\x01\x30\x01\x42\x31\n\x19io.pipeline.stream.engineB\x12\x45ngineServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031io.pipeline.stream.engineB\022EngineServiceProtoP\001'
  _globals['_PROCESSSTATUS']._serialized_start=234
  _globals['_PROCESSSTATUS']._serialized_end=287
  _globals['_PIPESTREAMRESPONSE']._serialized_start=79
  _globals['_PIPESTREAMRESPONSE']._serialized_end=232
  _globals['_PIPESTREAMENGINE']._serialized_start=290
  _globals['_PIPESTREAMENGINE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
