quarkus:
  http:
    port: 38006  # Dev port for test-harness module (matching application.yml)
    host: 0.0.0.0
  grpc:
    server:
      port: 38006  # Dev port for test-harness module (matching application.yml)
      host: 0.0.0.0
    clients:
      registration-service:
        host: localhost
        port: 38001
      testService:
        host: localhost
        port: 38006
  log:
    level: DEBUG
    console:
      enable: true
    category:
      "com.rokkon":
        level: DEBUG

# Registration service configuration for dev mode
registration:
  service:
    host: localhost
    port: 38001

# Module configuration for dev mode
module:
  auto-register:
    enabled: true  # Enable auto-registration in dev mode
