version: '3.8'

services:
  test-harness:
    image: pipeline/test-harness:latest
    container_name: test-harness
    ports:
      - "39100:39100"  # Standard module port
    environment:
      # Module configuration
      MODULE_AUTO_REGISTER_ENABLED: "true"
      MODULE_VERSION: "1.0.0"
      MODULE_TYPE: "test-harness"
      MODULE_METADATA: "category=testing,purpose=integration-testing"
      
      # Registration service configuration
      REGISTRATION_SERVICE_HOST: registration-service
      REGISTRATION_SERVICE_PORT: 39100
      
      # Consul configuration
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      
      # Java options
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
      
      # OpenTelemetry configuration (optional)
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "test-harness"
      OTEL_METRICS_EXPORTER: "prometheus,otlp"
      
    networks:
      - pipeline-network
    depends_on:
      - consul
      - registration-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:39100/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  pipeline-network:
    external: true